#!/usr/bin/env bash


system_upgrade() {
    if ! apt-get update
    then
        echo "Unable to update package list."
        return 1
    fi
    if ! apt-get dist-upgrade --allow-downgrades
    then
        echo "Unable to upgrade packages."
        return 1
    fi
    if ! apt-get dist-upgrade --allow-downgrades
    then
        echo "Unable to upgrade pinned packages."
        return 1
    fi
    if ! apt-get autoremove
    then
        echo "Unable to remove packages."
        return 1
    fi
}

pre_system_upgrade() {
    local soc="$(tr $"\0" $"\n" < /proc/device-tree/compatible | tail -n 1 | cut -d "," -f 2)"
    if grep -q -e "rk3588" -e "rk3588s2" -e "rk3528a" <<< "$soc"
    then
        sudo apt remove 8852be-dkms
    elif grep -q "rockchip" <(tr $"\0" $"\n" < /proc/device-tree/compatible | tail -n 1 | cut -d "," -f 1)
    then
        soc="rockchip"
    else
        soc=""
    fi
    if [[ -e /etc/apt/sources.list ]]
    then
        mv /etc/apt/sources.list /etc/apt/sources.list.bak
    fi

    for source in /etc/apt/sources.list.d/*.list
    do
        mv "$source" "$source.bak"
    done

    if [[ -d /etc/apt/preferences.d ]]
    then
        mv /etc/apt/preferences.d /etc/apt/preferences.d.bak
        mkdir /etc/apt/preferences.d
    fi

    if [ -n "$soc" ]
    then
        echo "Creating 80-radxa-"$soc".list"
        tee "/etc/apt/sources.list.d/80-radxa-"$soc".list" <<< "deb [signed-by=/usr/share/keyrings/radxa-archive-keyring.gpg] https://radxa-repo.github.io/"$soc"-bookworm/ "$soc"-bookworm main"
    fi

    for source in /usr/share/radxa-dist-upgrade/*.list
    do
        echo "$source"
        cp "$source" /etc/apt/sources.list.d/
    done
}

system_upgrade
pre_system_upgrade
system_upgrade
